bindPort = 9101
vhostHTTPPort = 9101
auth.token = ""
custom404Page = "404.html"
log.level = "trace"
webServer.addr = "mydongle.cloud"
webServer.port = 8101
webServer.user = ""
webServer.password = ""

[[httpPlugins]]
addr = "mydongle.cloud"
path = "/master/frpAuth.json"
ops = ["Login"]
