bindPort = 7000
vhostHTTPPort = 7000
auth.token = ""
custom404Page = "404.html"
log.level = "trace"
webServer.addr = "mydongle.cloud"
webServer.port = 7500
webServer.user = ""
webServer.password = ""

[[httpPlugins]]
addr = "mydongle.cloud"
path = "/master/frpAuth.json"
ops = ["Login"]
